<?php
require_once 'PHPUnit/Framework.php';

require_once '/Users/vincentbruijn2/Sites/colorscheme/scheme.class.php';

/**
 * Test class for ColorScheme.
 * Generated by PHPUnit on 2010-08-22 at 12:52:30.
 */
class ColorSchemeTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ColorScheme
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ColorScheme;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
?>
